Refactor MLine Media to follow qucs implementation
scikit-rf/scikit-rf pull request #650
Opened 2022-04-30 21:01 UTC by mhuser

Refactor MLine Media against [qucsator implementation](https://github.com/Qucs/qucsator/blob/develop/src/components/microstrip/msline.cpp) for reference, add test cases and modify some notebooks if required .

2022-05-01 19:50 UTC, jhillairet approved these changes
OK. Do you plan to add additional tests?

2022-05-01 19:50 UTC, jhillairet commented on skrf/media/mline.py
> +        * 'none'
could you add in the docstring the default values? Ex:

```
* 'kirschningjansen' (default)
* 'hammerstadjensen'
```

2022-05-01 19:58 UTC, mhuser commented
> OK. Do you plan to add additional tests?

Yes. It is still a work on progress. I still need to:

- [ ] Add a test for each model against qucs generated s-parameters
- [ ] Add a test to ensure warning is raised when t < 3*skin_depth 
- [ ] Repair some notebooks that use MLine
- [ ] Think more about this media attributes and docstrings e.g. if it provide `alpha_conductor` with `return self._alpha_conductor`

2022-05-01 20:00 UTC, mhuser commented
Of course I am open to more tests ideas !

2022-05-05 22:12 UTC, mhuser commented
Almost ready.
There is still the question if I add Wheeler and Schneider impedance models -not that much works to port these from qucs -
and also some more works to compare with the ads s-parameters provided by @JAnderson419 (may he be thanked a lot here)!

2022-05-06 16:29 UTC, jhillairet requested changes
just a comment concerning the name of the functions. Otherwise OK to me, thank you.

2022-05-07 12:30 UTC, mhuser commented on skrf/media/mline.py
> +    def analyseDielectric(self, ep_r: NumberLike, tand: NumberLike,
Indeed. Done.

2022-05-07 12:33 UTC, mhuser commented on skrf/media/tests/test_mline.py
> +
I am on that. Seems my implementation Djordjevic/Svensson dielectric frequency variation is not consistent with ADS one. This kind of dispersion does not exists in Qucs and was done from the paper.

2022-05-07 12:37 UTC, mhuser commented on skrf/media/tests/test_mline.py
> +
I am returning this PR to draft until either I understand or I write in the docstring that this functionnality is not well tested and lead to different results that other simulators.

2022-05-07 16:55 UTC, mhuser commented
Current state of consistency test between `mline` and with Djordjevic/Svensson dielectric frequency dispersion ADS.
Still some works left.
![image](https://user-images.githubusercontent.com/8080934/167264176-56348a71-f315-4ea6-9f29-a2f1760bcf34.png)

2022-05-14 13:18 UTC, mhuser commented
Agreement with ADS significantly improved.
Only a refinement of docstring still required. I will mention the papers reference for each methods.
![image](https://user-images.githubusercontent.com/8080934/168427395-a3666b20-7383-4379-ab10-e8a47e5760a6.png)

2022-05-14 16:27 UTC, mhuser commented on skrf/media/tests/test_mline.py
> +
The tests now pass and agree with ADS data. The limit for S11 at low-frequency has still to be 10x more than 0.1 dB and 1°, but this looks not bad at all and a lot better as before.

2022-05-15 19:40 UTC, Ttl commented
It looks like the second to last revert commit reverted also all the previous commits. There isn't currently any difference to the master branch.

I don't like the `compatibility_mode` parameter very much. Only one of the settings should be correct and I don't think we should try to keep compatibility with other simulator models. I don't think it's a parameter that many users would change anyway.

2022-05-15 20:08 UTC, mhuser commented
Looks like I created a git mess.

2022-05-15 20:20 UTC, mhuser commented
History now looks ugly, but the changes should be all back.

2022-05-15 20:32 UTC, mhuser commented
> I don't like the `compatibility_mode` parameter very much. Only one of the settings should be correct and I don't think we should try to keep compatibility with other simulator models. I don't think it's a parameter that many users would change anyway.

I understand your point of view, and this parameter make the code be less clear. It was more a trick to ease the comparison between both set of results. However, if we keep only one or the other behaviour, then we cannot test all functionalities against a known reference (some being implemented only in ADS or only in QUCS).

It could also be tough as an "almost hidden" feature, that most users would never change or be aware of. The question being which behaviour to pick as the default. From the elements you presented, the model closer to RGLC would be the ADS one, which will require some minor changes to notebooks before this PR could be merged.

Have you other ideas on how to handle this ?

2022-05-20 13:18 UTC, Ttl approved these changes

2022-05-21 06:48 UTC, jhillairet approved these changes
Great work, thank you!

2022-05-21 06:48 UTC, jhillairet commented
If you are OK to merge, let us know.

2022-05-21 06:56 UTC, mhuser commented
OK

2022-05-21 07:47 UTC, merged

2022-05-21 08:08 UTC, mhuser commented
Thank you so much !