Timescale
scikit-rf/scikit-rf pull request #900
Opened 2023-04-24 21:26 UTC by FranzForstmayr

This PR fixes several issues regarding time transformation.

to be continued

2023-04-24 21:46 UTC, FranzForstmayr commented
Some ongoing work to match the `t` vector from `impulse_response` (which looks good) with `Frequency.t`

2023-04-25 09:02 UTC, mhuser commented
> Some ongoing work to match the `t` vector from `impulse_response` (which looks good) with `Frequency.t`

Beware pitfall with [fft](https://numpy.org/doc/stable/reference/generated/numpy.fft.fftfreq.html) vs [rfft](https://numpy.org/doc/stable/reference/generated/numpy.fft.rfftfreq.html). They do not return the same number of samples. I often stumble inside 😉

2023-04-25 10:14 UTC, FranzForstmayr commented
I am aware of the computational difference, but both methods expect the first sample to be the DC component. 
In a band pass measurement I'm not sure if the interpretation of time signals make any physical sense without DC extrapolation.
Correct me if I'm wrong.

2023-04-25 10:15 UTC, FranzForstmayr commented
Copied from #860 

```python
# Current behaviour
f = rf.Frequency(10, 50, 5)
f.t 
array([-5.0e-11, -2.5e-11,  0.0e+00,  2.5e-11,  5.0e-11]) # 25 ps would imply 40 GSps = 20GHz

# PR 900 now
f = rf.Frequency(10, 50, 5)
f.t 
array([-4.0e-11, -2.0e-11,  0.0e+00,  2.0e-11,  4.0e-11]) # 20 ps would imply 50 GSps = 25 GHz

# I would like to have when PR900 is finished
f = rf.Frequency(10, 50, 5)
f.t 
array([-5.0e-11, -4.0e-11, -3.0e-11, -2.0e-11, -1.0e-11 0.0e+00,  1.0e-11, 2.0e-11, 3.0e-11, 4.0e-11]) # 10 ps would imply 100 GSps = 100 GHz
```

2023-04-25 14:16 UTC, mhuser commented
> In a band pass measurement I'm not sure if the interpretation of time signals make any physical sense without DC extrapolation.

According to the Agilent note presented by @Vinc0110  in #757, the bandpass mode without dc still show location and amplitude of discontinuities in impulse response, but not their capacitive or inductive nature. The frequency requirement are less stringent, e.g. no harmonic sweep required. 
 
![image](https://user-images.githubusercontent.com/8080934/234304232-fb4fd316-90d1-484c-a80b-7a25e10583b2.png)

2023-04-25 15:04 UTC, FranzForstmayr commented
Can you calculate this with an ordinary `ifft`? I think one would need something like [STFT](https://en.wikipedia.org/wiki/Short-time_Fourier_transform) to calculatate arbitrary ranges. We do not pass the frequency vector to the `ifft` currently, so we assume frequency is starting at 0.

2023-04-26 14:08 UTC, FranzForstmayr commented
> But in the above code to plot the time domain of s-parameters, which should be equivalent to bandpass, it is like half of the frequency vector will be considered as negative frequencies, which left me confused. It probably works, but how?

I'm also not sure how to interprete the result.
> In a band pass measurement I'm not sure if the interpretation of time signals make any physical sense without DC extrapolation.

The current implementation does not care if I pass 0-5GHz, 1-6GHz or 50-55GHz, which seems strange to me.

2023-04-26 14:41 UTC, mhuser commented
> > But in the above code to plot the time domain of s-parameters, which should be equivalent to bandpass, it is like half of the frequency vector will be considered as negative frequencies, which left me confused. It probably works, but how?
> 
> I'm also not sure how to interprete the result.

Ok, in [this source](https://www.researchgate.net/publication/261779218) I think I found half of the answer:
Du to the periodic nature of fft (that's also why we can shift it), it can also be seen as positive-only frequency vector only from 0 to Fs. This would be consistant with skrf implementation.
![image](https://user-images.githubusercontent.com/8080934/234610164-28455eb4-94fc-4e08-9438-ca02b3596826.png)

But it does not answer our question on how to interpret the bandpass nature of the frequency vector when it start far away 0.

2023-04-26 17:52 UTC, Vinc0110 commented
Hi guys.
I'm loving the discussion, but I currently don't have time to dig into the details. Hopefully I can have a closer look over the weekend. 

This whole uncertainty is exactly what irritated me in issue #860. A benchmark result from another tool - known to be correct - would be perfect to compare our implementation against.

2023-04-27 09:11 UTC, mhuser commented
> This whole uncertainty is exactly what irritated me in issue #860. A benchmark result from another tool - known to be correct - would be perfect to compare our implementation against.

Maybe a brave VNA measurer could measure a length + short and save .s1p as well as bandpass time serie?

In the meantime, I have found that bandpass frequency data seems to be related to *downsampling* if the fft coefficients are 0 between 0 and a start frequency. The source [Oppenheim, Schafer, Discrete-Time Signal Processing](https://research.iaun.ac.ir/pd/naghsh/pdfs/UploadFile_2230.pdf) is often cited and contains following figure:
![image](https://user-images.githubusercontent.com/8080934/234808962-5238ad52-d740-490e-b4d5-28dd05591a15.png)

Unfortunately, I did not found in the book neither how the time vector is reconstructed if the inverse fft is done nor how the time data are supposed to looks like.

2023-04-27 10:37 UTC, FranzForstmayr commented
We could also make a separate Issue/PR for the bandpass stuff and finish this one.
This PR fixes a one off error for the window, the sampling frequency for baseband measured time visualizations and passes the window specification through `plot_s_db_time` for now.

2023-04-27 19:10 UTC, mhuser commented
I think I have got it. I asked a colleague that is much more skilled in signal processing than me and he gave me the interpretation that was later confirmed by the appendix B of [Agilent AN 1287-8 Simplified Filter Tuning Using Time Domain](https://xdevs.com/doc/HP/pub/5968-5328E.pdf)

Radio signal transmission - e.g. AM - modulates a carrier frequency with data, which creates sidebands around it. For demodulation, the time-domain data can be multiplied by the carrier frequency, which centers the side bands around 0 Hz and then low-passed to remove the higher-frequencies content.
Bandpass TDR just does that, but because we already are in the frequency domain we just have to pretend that the center frequency of the band is 0 Hz *et voilà*, demodulation done. Because the spectrum is not symmetric, this will give complex data representing the demodulated [I and Q signals](https://en.wikipedia.org/wiki/In-phase_and_quadrature_components). Hence, to locate discontinuities, magnitude should be observed.

> In this mode, the center frequency of the frequency
> sweep is effectively translated to DC, and the
> inverse Fourier transform is applied from minus
> one-half of the frequency span to plus one-half of
> the span. This is important when looking at a band-
> pass filter with a frequency response that is the
> same as a low-pass filter response translated up in
> frequency to the center of the bandpass filter.
> The time-domain transform represents the return
> loss as a function of length through the device
> under test. For time-domain transforms to be
> useful, they must have enough resolution to resolve
> the distinguishing characteristics of the network
> being measured. In general, the resolution of a
> transform is inversely proportional to the frequency
> span, although in bandpass mode the resolution
> is reduced by half because half the span is for neg-
> ative frequencies and half for positive frequencies.

2023-04-27 19:11 UTC, mhuser commented
> We could also make a separate Issue/PR for the bandpass stuff and finish this one.

Indeed. Maybe should we still wait Monday to let @Vinc0110 have a look if he meet the occasion.

2023-04-27 19:44 UTC, mhuser commented
```Python
import skrf as rf
import numpy as np

f0 = 10e9
f1 = 50e9
n = 5
f = rf.Frequency(f0, f1, n, unit = 'Hz')

# bandpass frequency and time step
df = (f1 - f0) / (n - 1)
dt = 1 / df

# fft frequency vector
ff1 = np.array([-2, -1, 0, 1, 2]) * df / 5
print(f'{ff1} [Hz]')
ff2 = np.fft.fftshift(np.fft.fftfreq(n, 1/df))
print(f'{ff2} [Hz]')

# fft time vector
tt1 = np.array([-2, -1, 0, 1, 2]) * dt / 5
print(f'{tt1} [s]')
tt2 = np.fft.fftshift(np.fft.fftfreq(n, 1/dt))
print(f'{tt2} [s]')

# output:
[-4.e+09 -2.e+09  0.e+00  2.e+09  4.e+09] [Hz]
[-4.e+09 -2.e+09  0.e+00  2.e+09  4.e+09] [Hz]
[-4.e-11 -2.e-11  0.e+00  2.e-11  4.e-11] [s]
[-4.e-11 -2.e-11  0.e+00  2.e-11  4.e-11] [s]
```

2023-04-27 19:54 UTC, FranzForstmayr commented
Ok, thank you for this nice paper :)

But then I think that we serve the values for `ifft` in a wrong order.

From numpy's doc:

>The input should be ordered in the same way as is returned by [fft](https://numpy.org/doc/stable/reference/routines.fft.html#module-numpy.fft), i.e.,
>a[0] should contain the zero frequency term,
>a[1:n//2] should contain the positive-frequency terms,
>a[n//2 + 1:] should contain the negative-frequency terms, in increasing order starting from the most negative frequency.

We calculate the ìfft`like this:
```
return npy.fft.fftshift(npy.fft.ifft(x, axis=0), axes=0)
```
where `x[0]` is our lowest frequency, which is the most negative one. So I think we have to `ifftshift` the values first.

2023-04-27 20:06 UTC, mhuser requested changes
Best if my understanding would be confirmed by someone else.

2023-04-27 20:06 UTC, mhuser commented on skrf/frequency.py
> +        t_period = (n-1)/f_step
`t_period = 2*(n-1)/f_step` because half of the frequency vector is considered like the negative frequencies

2023-04-27 20:06 UTC, mhuser commented on skrf/frequency.py
> +        t_period = (n-1)/f_step
`t_period = 2*(n-1)/f_step` because half of the frequency vector is considered like the negative frequencies

2023-04-27 20:12 UTC, mhuser commented
> But then I think that we serve the values for `ifft` in a wrong order.

Oh! I think you are right! Nice spotted!

2023-04-27 20:16 UTC, mhuser approved these changes

2023-04-28 06:22 UTC, mhuser requested changes
![image](https://user-images.githubusercontent.com/8080934/235070078-2f517c91-b5f1-4d18-aff4-20dcdbec90f0.png)

Plot of s-parameter n,m is broken.

2023-04-28 07:34 UTC, FranzForstmayr commented
> @FranzForstmayr Can you try this? (edit: plot without dc extrapolation for bandpass)
> 
> ```python
> import skrf as rf
> from skrf.media import Freespace
> from matplotlib import pyplot as plt
> rf.stylely()
> 
> f = rf.Frequency(10, 50, 5, unit = 'GHz')
> m = Freespace(f, z0 = 50)
> n = m.delay_short(10, unit = 'ps')
> n_dc = n.extrapolate_to_dc()
> window = 'boxcar'
> plt.figure()
> plt.title('The 10ps short network')
> n_dc.plot_s_time_impulse(window = window, pad = 0, label = 'plot_s_time_impulse')
> n_dc.plot_s_time_step(window = window, pad = 0, label = 'plot_s_time_step')
> n.plot_s_time_mag(label = 'plot_s_time_mag')
> ```

This looks good!
![test](https://user-images.githubusercontent.com/9936788/235083985-5130647f-d368-471d-9726-81deb3d7b209.png)

2023-04-28 07:42 UTC, mhuser approved these changes

2023-04-28 07:44 UTC, mhuser commented
Great! Nice, the time for the reflexion going back and forth and the resolution divided by two for bandpass are clearly visibles!

2023-05-03 07:14 UTC, merged